#!/bin/bash

bids_root="/home/orco/data/VentrikelCNN"
dev_path="$bids_root/derivatives/fastsurfer"
mkdir -p $dev_path
cd $bids_root
subs=($(ls -d sub*))


cd $dev_path

for i in ${subs[@]}
do
  echo $i
  mkdir -p $i
  if [ -e $bids_root/$i/ses-01/anat/${i}*_ses-01_T1w.nii ]
  then
    pigz $bids_root/$i/ses-01/anat/${i}*_ses-01_T1w.nii
  fi
  if [ ! -e $dev_path/$i/orig.mgz ]
  then
    src="$bids_root/$i/ses-01/anat/${i}*_T1w.nii.gz"
    dest="$dev_path/$i/orig.mgz"
    echo "src: $src"
  	mri_convert $src $dest
  fi
done

exit 0
