#!/bin/bash

## Install enviroment:
# conda create -n fastsurfer
# conda activate fastsurfer
# conda install pytorch torchvision cudatoolkit=11 cudnn -c pytorch
# conda install -c conda-forge numpy scipy scikit-image cycler decorator h5py imageio kiwisolver matplotlib nibabel Pillow pyparsing PyWavelets scikit-image six

#Fastsurfer needs freesurfer 6
export FREESURFER_HOME="/usr/local/freesurfer_6"
#/fast/users/dellorca_c/work/freesurfer-6
source $FREESURFER_HOME/SetUpFreeSurfer.sh

bids_root="/home/orco/data/VentrikelCNN"

der_dir="${bids_root}/derivatives/fastsurfer"
export FASTSURFER_HOME="/home/orco/software/FastSurfer"

#Grab subject IDs
cd $bids_root
subs=($( ls -1d sub-V* ))
#subs=( 'sub-N208' )
echo ${subs[@]}

#mkdir -p $der_dir
cd $der_dir
for sub in ${subs[@]}
do
    echo "$sub"
    # If doesnt exist convert nii to mgz
    if [ ! -e ${der_dir}/${sub}/orig.mgz ]
    then
      mkdir -p ${der_dir}/${sub}
      #mri_convert $bids_root/$i/ses-01/anat/${i}*_T1w.nii.gz ${der_dir}/${sub}/orig.mgz
    fi
    #if [ ! -e "${der_dir}/${sub}/mri/aparc.DKTatlas+aseg.deep.mgz" ]
    #then
      export SUBJECTS_DIR=${der_dir}
      $FASTSURFER_HOME/run_fastsurfer.sh --seg_only \
                          --sd ${der_dir} \
                          --sid $sub \
                          --t1 ${der_dir}/${sub}/orig.mgz \
                          --parallel --threads 25 --vol_segstats
    #else
    #  echo "$sub seg found! skipping"
    #fi
done
